# Generated by Django 4.0.2 on 2022-12-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_post111_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post111',
        ),
    ]
